apiVersion: v1
kind: Service
metadata:
  name: {{ template "fullname" . }}-wordpress
  labels:
    app: {{ template "fullname" . }}-wordpress
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  selector:
    app: {{ template "fullname" . }}-wordpress
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: http
  - name: https
    protocol: TCP
    port: 443
    targetPort: https
