{{- if .Values.ingress.enabled }}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "fullname" . }}-wordpress
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
  annotations:
{{- if .Values.ingress.ssl }}
    ingress.kubernetes.io/ssl-redirect: "true"
    kubernetes.io/tls-acme: "true"
{{- else }}
    ingress.kubernetes.io/ssl-redirect: "false"
{{- end }}
spec:
{{- if .Values.ingress.ssl }}
  tls:
  - secretName: {{ template "fullname" . }}-{{ .Values.ingress.host }}
{{- if .Values.ingress.host }}
    hosts:
    - {{ .Values.ingress.host }}
{{- end }}
{{- end }}
  rules:
  - http:
      paths:
      - backend:
          serviceName: {{ template "fullname" . }}-wordpress
          servicePort: http
{{- if .Values.ingress.host }}
    host: {{ .Values.ingress.host }}
{{- end }}
{{- end }}
